version: '2'

services:

### Nginx Server Container ##################################

    nginx:
        build: ./nginx
        restart: unless-stopped
        volumes:
            - ./app/:/var/www/html
        environment:
            VIRTUAL_HOST: app.dev # For nginx-proxy https://github.com/jwilder/nginx-proxy
        expose:
            - "80"
            - "443"
        networks:
            - proxy
            - default

### PHP Container ###########################################

    php:
        build: ./php
        restart: unless-stopped
        volumes:
            - ./app/:/var/www/html

### MySQL Container #########################################

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        volumes:
            - ./mysql/data/:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

networks:
    proxy:
        external:
            name: proxy_default
