version: '2'

services:

### Nginx Server Container ##################################

    nginx:
        build: ./nginx
        restart: unless-stopped
        volumes:
            - ./app/:/var/www/html
        networks:
            - proxy
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:app.test"
            - "traefik.docker.network=traefik_webgateway"

### PHP Container ###########################################

    php:
        build: ./php
        restart: unless-stopped
        volumes:
            - ./app/:/var/www/html

### MySQL Container #########################################

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        volumes:
            - ./mysql/data/:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

networks:
    proxy:
        external:
            name: traefik_webgateway
