version: '2'

services:

### Nginx Server Container ##################################

    nginx:
        build: ./nginx
        restart: unless-stopped
        volumes_from:
            - php
        volumes:
            - ./nginx/logs/:/var/log/nginx
        links:
            - php
        environment:
            VIRTUAL_HOST: app.local # For nginx-proxy https://github.com/jwilder/nginx-proxy
        expose:
            - "80"
            - "443"
        networks:
            - proxy
            - default

### PHP Container ###########################################

    php:
        build: ./php
        restart: unless-stopped
        volumes:
            - ./app/:/var/www/laravel
            - ./php/logs/:/usr/local/var/log/php
        expose:
            - "9000"
        networks:
            - default

### MySQL Container #########################################

    mysql:
        build: ./mysql
        restart: unless-stopped
        volumes:
            - ./mysql/data/:/var/lib/mysql
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        links:
            - php
        networks:
            - default
    
networks:
    proxy:
        external:
            name: proxy_network
